### ISSUE TITLE
Identity 2.0

### ISSUE THREAD

**Issue by lnu** [milesibastos/NHibernate.AspNet.Identity#16]
Hi,

I created a fork of your project and I implemented everything for Identity 2.0(based on ef implemenation). If you're interested I can create a pull request. The only thing is I still use the string Id of V1. 

Thanks for the initial project.

Laurent

**Comment by acastaner** [comment]
Are there any plan to make a NuGet package out of this branch, or to fork the Identity 2.0 branch? I realize the above comment says it's simple to do, but I would prefer to go through NuGet if at all possible - if not I will just do as Inu suggested.

**Comment by lnu** [comment]
I understand but it's not my work in the first place. Probably the easiest would be to merge the changes into the original repo but there is no response from the owner.

**Comment by hazzik** [comment]
@lnu just submit a pull request. /cc @milesibastos

**Comment by lnu** [comment]
The pull request has been merged, the version updated to match Asp.Net Identity release and the new version pushed to nuget.
Thanks @milesibastos

**Comment by milesibastos** [comment]
thks to u for a great job!
