### ISSUE TITLE
Add an option to drop transaction scopes

### ISSUE THREAD

**Issue by DennisFrostlander** [milesibastos/NHibernate.AspNet.Identity#23]
Out of curiosity - why do you use TransactionScopes? 
In my mind, they only stand in the way of sharing the ISession/Transaction that I already have in my app anyway. This is because when the transaction scope is completed the current session's transaction is no longer usable.

Basically, my scenario is this:
I already have an app/website with ISession open per request. I also have the current transaction obtained by calling Session.BeginTransaction which I commit or rollback at the end of the request. Naturally, I would like to reuse the same transaction for identity management so that all my work is committed or rolled back together. However, I cannot do so because my current transaction gets enlisted into the transaction scope and gets committed for me inside the UserStore.

**Comment by lnu** [comment]
I have a dev branch where all TransactionScope have been replaced by NHibernate transaction. It fixes the autoflush issue with TransactionScope and workws if embedded inside a global TransacationScope.
https://github.com/lnu/NHibernate.AspNet.Identity/tree/NoComponent

**Comment by DennisFrostlander** [comment]
Could you also consider to check if a transaction is already open before creating/committing a new one? Otherwise, my scenario above will still not be satisfied because all asp.net identity work will be committed on the separate transaction and I want it to happen on my own transaction together will all other updates/inserts/deletes that I am doing while creating/deleting user account, for example.
(I am just not sure how to check if ISession.BeginTransaction has already been called, perhaps you can check Transaction.IsActive flag, but not sure how reliable that is).

Regarding the transaction scope, I am just wondering - why care so much about it in the component like yours? You abstract yourself from data access by requiring an ISession and creating/committing transactions on it when necessary. The rest is up to how NHibernate handles enlistment of transactions into the transaction scopes if the caller of your code wishes to use those. Somewhere it works, somewhere it doesn't...

**Comment by lnu** [comment]
I think the stuff with the TransactionScope starts from here:https://github.com/milesibastos/NHibernate.AspNet.Identity/pull/5
Let's face it: it fixed an issue and works in most case but as you pointed id, it brings lots of bad stuff with transaction management. 
Probably the best would be to drop all transactions from the library and let people manage it from outside. But it should be clear that every call to the library should be enclosed in an nhibernate transaction(or manage flushes yourself) or you could face strange side effects.

**Comment by lnu** [comment]
I made the changes in this branch https://github.com/lnu/NHibernate.AspNet.Identity/tree/2.0
Now the behaviour is the same as the EF provider.

**Comment by DennisFrostlander** [comment]
Thanks! 

One other thing that I noticed is that flushing the context is not consistent. For example, create/update/delete methods are flushing, but all others (AddLoginAsync and others) are not. 
Not sure why explicit flushing is needed, but that's another topic I guess.
P.S. For example, in most of my NHibernate apps I am using FlushMode.Commit because it's much faster to send all inserts/updates in a single batch at commit time...

**Comment by lnu** [comment]
Flush is only done int he save/update/delete methods of each store. For example, the AddLoginAsync only adds a login to the logins collection. BUT when you use the UserManager, it calls the Update method of the UserStore right after so it flushes everything(https://aspnetidentity.codeplex.com/SourceControl/latest#src/Microsoft.AspNet.Identity.Core/UserManager.cs).

**Comment by DennisFrostlander** [comment]
Oh, ok. I did not see that. But that was anyway an off-topic. I think this issue is resolved now, so feel free to close it according to your workflow.

**Comment by lnu** [comment]
Thank you for the feedback. We'll see if it can be merged.

**Comment by hazzik** [comment]
@lnu is your version available at nuget?

**Comment by lnu** [comment]
No. I'm waiting for @milesibastos  to merge and publish.

**Comment by hazzik** [comment]
:+1:
