### ISSUE TITLE
Mysql 5.6 When using SchemaExport I am getting this issue "BLOB/TEXT column 'UserName' used in key specification without a key length"

### ISSUE THREAD

**Issue by dags20** [milesibastos/NHibernate.AspNet.Identity#33]
I am using the code that you have on the Sample folder for version 2.2.0. What I am doing is trying to export the sql squema to a file same as you do for the sqlite version.

This is the squema that I am getting.

   create table AspNetUsers (
        Id VARCHAR(255) not null,
       AccessFailedCount INTEGER,
       Email VARCHAR(255),
       EmailConfirmed TINYINT(1),
       LockoutEnabled TINYINT(1),
       LockoutEndDateUtc DATETIME,
       PasswordHash VARCHAR(255),
       PhoneNumber VARCHAR(255),
       PhoneNumberConfirmed TINYINT(1),
       TwoFactorEnabled TINYINT(1),
       UserName TEXT not null unique,
       SecurityStamp VARCHAR(255),
       primary key (Id)
    )

Any Idea on what can be the problem ?

**Comment by milesibastos** [comment]
set map.Length(255);

**Comment by dags20** [comment]
That is already on your code 

IdentityUser.cs

this.Property(x => x.UserName, map =>
            {                
                map.Length(256);
                map.NotNullable(true);
                map.Unique(true);
            });

This seems to me more like an issue on the nhibernate code.. maybe !

**Comment by milesibastos** [comment]
map.Length > 255 = BLOB/TEXT and not indexed...
I do fix map soon...
but at time, change "map.Length(256);" to "map.Length(255);" and run MapTests

P.S: Roles have the same problem!

**Comment by lnu** [comment]
Sorry for that. I changed it to match the EF provider.
  Same mistake here: `https://aspnet.codeplex.com/SourceControl/latest#Samples/Identity/AspNet.Identity.MySQL/MySQLIdentity.sql` you'll see they also use chars with a length of 256.

**Comment by lnu** [comment]
I changed it to 256 to match EF but I shouldn't have done that. The length can be removed from the mapping and it will be 255 for any dialects.

**Comment by dags20** [comment]
I changed it to 255 and it worked. Thank you.
